# Generated by Django 2.2 on 2019-04-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190429_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_acesso',
            field=models.DateTimeField(),
        ),
    ]
